name: Release

concurrency:
  group: '${{ github.workflow }}'
  cancel-in-progress: true

on:
  workflow_dispatch:

jobs:
  release:
    name: Lint, build, check, test & release

    runs-on: ubuntu-latest
    timeout-minutes: 10

    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/backend

      - name: Configure git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Create release PR
        run: make release
        env:
          DEPLOYER_ACCESS_TOKEN: '${{ secrets.DEPLOYER_ACCESS_TOKEN }}'

      - name: Create GitHub release
        run: |
            PREVIOUS_RELEASE=$(gh api repos/{owner}/{repo}/releases/latest --jq '.tag_name')
            gh release create release-${{ github.run_number }} \
                --title "Release ${{ github.run_number }}" \
                --generate-notes \
                --notes-start-tag ${PREVIOUS_RELEASE}
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
