name: Python Code Quality Assurance
description: Lint, checks & tests

inputs:
  working-directory:
    description: The working directory to run the commands in

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up uv
      uses: astral-sh/setup-uv@v6
      with:
        python-version: "3.12"
        activate-environment: true
        enable-cache: true

    - name: Install dependencies
      run: |
        make install-pipeline
      working-directory: ${{ inputs.working-directory }}
      shell: bash

    - name: Test
      run: |
        make test
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      env:
        RUFF_OUTPUT_FORMAT: github
