name: Release

concurrency:
  # Only one release job can run at a time
  group: ${{ github.workflow }}

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release HIdP Wagtail

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # A build is created as part of the QA job
      - name: Linting, checks & tests
        uses: ./.github/actions/python-qa

      - name: Determine release type
        run: |
          echo "is_prerelease=$(echo ${{ github.ref }} \
          | grep -qE '[.-](dev|rc)[.-]?[0-9]+$' && echo true || echo false)" \
          >> $GITHUB_OUTPUT
        id: is_prerelease

      - name: Release to DevPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: ${{ secrets.DEVPI_USERNAME }}
          password: ${{ secrets.DEVPI_PASSWORD }}
          repository-url: https://${{ secrets.DEVPI_USERNAME }}:${{ secrets.DEVPI_PASSWORD }}@devpi.leukeleu.nl/leukeleu/${{ fromJson(steps.is_prerelease.outputs.is_prerelease) && 'dev' || 'prod' }}/
          packages-dir: ./dist
